apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-tst
spec:
  storageClassName: azurefile-tst-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: nktst-secret
    secretNamespace: nk-tst
    shareName: sharetstdemo
    readOnly: false
  mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl