kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile-tst-sc
provisioner: kubernetes.io/azure-file
mountOptions:
  - mfsymlinks
  - actimeo=30 
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Premium_LRS
  storageAccount: satstdemo
  resourceGroup: rs-uni-webs-aks-pd-iogt