apiVersion: v1
kind: Secret
metadata:
  name: azure-file-share-secret
type: Opaque
data:
  azurestorageaccountname: c2F0c3RkZW1v 
  azurestorageaccountkey: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXNhdHN0ZGVtbztBY2NvdW50S2V5PTZldVhUcHRZdUFwc21sS2ZVWG54WWRuYmlkcU1ZZjBWb2FHVFdVR3pPOXM5azhPWTg3Rm9BSTcrV3k1R0l1ZzJIZFdybHhlSVl1Vjk4cTF5bEoraENnPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-file-share-deployment
spec:
  selector:
    matchLabels:
      app: azure-file-share-sample
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-file-share-sample
    spec:
      containers:
      - name: azure-file-share-sample
        image: nkem/imagereader:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
        - name: azure-fs
          mountPath: /app/mnt/azure
      volumes:
      - name: azure-fs
        azureFile:
          secretName: azure-file-share-secret
          shareName: sharetstdemo
          readOnly: true